version: '3.8'

services:
  db:
    image: postgres:16
    container_name: postgres_phonebook
    environment:
      POSTGRES_USER: admin 
      #PGHOST: localhost 
      PGUSER: admin 
      PGDATABASE: phonebook
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: phonebook
    volumes:
      - phonebook-db:/var/lib/postgresql/data
      - ./data:/tmp/init_data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "phonebook"]
      interval: 5s
      timeout: 5s
      retries: 5

  restore:
    image: postgres:16
    volumes:
      - ./data:/tmp/init_data
    restart: "no"
    environment:
      PGHOST: db 
      PGUSER: admin 
      PGPASSWORD: admin 
      PGDATABASE: phonebook 
    command: ["pg_restore", "-h", "$PGHOST", "-U", "$PGUSER", "-d", "$PGDATABASE", "/tmp/init_data/data.dump"]
    depends_on:
      db:
        condition: service_healthy

  server:
    build: .
    environment:
      DATABASE_URL: postgres://admin:admin@db:5432/phonebook
    volumes:
      - ./tmp:/tmp
    ports:
      - "5000:5000"
    depends_on:
      - db

volumes:
  phonebook-db:

